name = "discipline-baby"
main = ".open-next/worker.js"
compatibility_date = "2024-05-02"

[[kv_namespaces]]
binding = "KV"
# id = "YOUR_KV_NAMESPACE_ID"

[vars]
# Add your environment variables here
# DATABASE_URL = "..."

[site]
bucket = ".open-next/assets"
